[eiko.package]
name = "aws"
version = "0.0.1"
author = "kazaamjt"
author_email = "kazaamjt@gmail.com"
license = "MIT"
source_dir = "aws"
eikobot_version = ">=0.7.2"
github_name = "eikobot/AWS"
