[eiko.package]
name = "aws"
version = "0.1.0"
description = ""
long_description = ""
long_description_content_type = "text/markdown"
author = "kazaamjt"
author_email = "kazaamjt@gmail.com"
license = "MIT"
source_dir = "aws"
eikobot_requires = ">=0.7.0"
requires = []
